import { z } from "zod";

export const pickRandomMealInputSchema = {
  providedOptions: z.boolean().optional().describe("Whether to use a model provided list of options"),
  options: z.array(z.object({
    type: z.enum(["dish", "restaurant"]).describe("Type of the option"),
    title: z.string().describe("Name of the dish or restaurant"),
    cuisine: z.string().optional().describe("Cuisine of the dish or restaurant"),
    description: z.string().describe("Brief description"),
    phone: z.string().optional().describe("Phone number (for restaurants)"),
    address: z.string().optional().describe("Physical address (for restaurants)"),
  })).optional().describe("List of options to choose from if providedOptions is true"),
};

export const formatRecipesInputSchema = {
  type: z.enum(["dish", "restaurant"]).describe("Type of the options"),
  dish_details: z.string().optional().describe("Details about the dish"),
  restaurant_details: z.string().optional().describe("Details about the restaurant"),
  options: z.array(z.object({
    title: z.string().describe("Title of the option"),
    description: z.string().describe("Description of the option"),
  })).describe("List of recipe or restaurant options, generated by the model based on the input and user preferences in the format [{title: '...', description: '...'}]"),
};
